services:
  web:
    build: .
    image: php:8.4-apache
    ports:
      - "0:80"
    volumes:
      - ./:/var/www
      - ./public.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      PHP_DISPLAY_ERRORS: 1
      PHP_ERROR_REPORTING: E_ALL
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "0:3306"
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: dmit2025
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "0:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: studentpass
    depends_on:
      - mysql
